# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Lean Formalization Lab
description: "Pioneering certified proofs and algorithms in Lean 4"
baseurl: ""
url: "https://sanghyeok0.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

remote_theme: eliottvincent/bay

header:
  pages:
    - name: Home
      slug: /                # 메인 페이지
    # - name: Lab
    #   slug: /about/          # 연구실 소개 (about.md)
    - name: People
      slug: /people/         # 구성원 페이지
    # - name: Research
    #   slug: /research/       # 연구 주제 개요
    - name: Projects
      slug: /projects/       # 개별 프로젝트 상세
    - name: Publications
      slug: /publications/   # 논문·성과 목록
    # - name: News
    #   slug: /news/           # 세미나·이벤트 공지
    - name: Links
      slug: /links/
    # - name: Resources
    #   slug: /resources/      # 코드·데이터·강의자료
    # - name: Contact
    #   slug: /contact/        # 연락처 페이지

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: yourmail@domain.com
    - type: wechat
      value: YourWeChatUsername
      link: "#"
  follow:
    - type: twitter
      name: Twitter
      link: http://twitter.com/YourTwitterUsername
      username: "@YourTwitterUsername"
    - type: facebook
      name: Facebook
      link: http://facebook.com/YourFacebookUsername
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername
    - type: github
      name: GitHub
      link: http://github.com/YourGitHubUsername
    - type: dribbble
      name: Dribbble
      link: https://dribbble.com/YourDribbbleUsername
    - type: rss
      name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-remote-theme

target_blank:
  enabled: true
  rel: "noopener"
  whitelist:
    - "/links/"

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
